sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "boiler01_temperatur_oben"
    register_type: read
    address: 1630
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "boiler01_pumpe_ansteuerung"
    id: "boiler01_pumpe_ansteuerung"
    register_type: read
    address: 1632
    unit_of_measurement: "%"
    value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "boiler01_gewuenschte_boilertemperatur"
    address: 1631
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 100

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "boiler01_nachladen_wenn_boilertemperatur_unter"
    address: 1632
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 1
    max_value: 90

binary_sensor:
  - platform: template
    name: "boiler01_pumpe_an_aus"
    lambda: |-
      if (id(Boiler_1_Pumpe_Ansteuerung).state > 0) {
        return true;
      } else {
        return false;
      }
