sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_vorlauf_isttemperatur"
    register_type: read
    address: 1030
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_vorlauf_solltemperatur"
    register_type: read
    address: 1031
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_pumpe_an_aus"
    register_type: coil
    address: 1029

number:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_vorlauf_temperatur_10c_aussentemperatur"
    address: 1031
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 110

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_vorlauf_temperatur_minus_10c_aussentemperatur"
    address: 1032
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 110

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_absenkung_der_vorlauftemperatur_im_absenkbetrieb"
    address: 1033
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 0
    max_value: 70

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet"
    address: 1036
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: -20
    max_value: 50

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet"
    address: 1037
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: -20
    max_value: 50

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_frostschutztemperatur"
    address: 1038
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: -10
    max_value: 20

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als"
    address: 1039
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 30

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird"
    address: 1047
    unit_of_measurement: "°C"
    value_type: U_WORD
    min_value: 60
    max_value: 120

select:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "hk01_betriebsart"
    address: 8046
    value_type: U_WORD
    optionsmap:
      "Aus": 0
      "Automatik": 1
      "Extraheizen": 2
      "Absenken": 3
      "Dauerabsenken": 4
      "Partybetrieb": 5
