sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_temperatur"
    register_type: read
    address: 0
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_abgastemperatur"
    register_type: read
    address: 1
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_verbleibende_heizstunden_bis_zur_asche_entleeren_warnung"
    register_type: read
    address: 86
    unit_of_measurement: "h"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_saugzug_ansteuerung"
    register_type: read
    address: 13
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_saugzugdrehzahl"
    register_type: read
    address: 6
    unit_of_measurement: "rpm"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_sauerstoffregler"
    register_type: read
    address: 16
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_restsauerstoffgehalt"
    register_type: read
    address: 3
    unit_of_measurement: "%"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_ruecklauffuehler"
    register_type: read
    address: 9
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_primaerluft"
    register_type: read
    address: 11
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_sekundaerluft"
    register_type: read
    address: 13
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_betriebsstunden"
    register_type: read
    address: 20
    unit_of_measurement: "h"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_stunden_seit_letzter_wartung"
    register_type: read
    address: 55
    unit_of_measurement: "h"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_betriebsstunden_in_der_feuererhaltung"
    register_type: read
    address: 24
    unit_of_measurement: "h"
    value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_solltemperatur"
    address: 0
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 70
    max_value: 90

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "kessel_bei_welcher_rl_temperatur_an_der_zirkulationsleitung_soll_die_pumpe_ausschalten"
    address: 600
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 20
    max_value: 120

binary_sensor:
  - platform: template
    name: "kesselzustand_heizen"
    lambda: |-
      if (id(kessel_zustand).state == "Heizen") {
        return true;
      } else {
        return false;
      }
